In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv(r'C:\Users\akash\Desktop\HackerEarth\HackerEarth Machine Learning Challenge - Carnival Wars!\dataset\train.csv')
df_test = pd.read_csv(r'C:\Users\akash\Desktop\HackerEarth\HackerEarth Machine Learning Challenge - Carnival Wars!\dataset\test.csv')

df_train.head(3)

,Product_id,Stall_no,instock_date,Market_Category,Customer_name,Loyalty_customer,Product_Category,Grade,Demand,Discount_avail,charges_1,charges_2 (%),Minimum_price,Maximum_price,Selling_Price
0,BRAE2NF6JA5GUEXG,37.0,2015-08-22 18:36:12.000,2,Lillyann,Yes,Fashion,1,68,0.0,376.0,11.0,2983.0,4713.0,4185.947700
1,TUNE8SFB6RJN2HSD,38.0,2016-03-27 21:19:13.000,24,Klynn,Yes,Fashion,0,51,0.0,397.0,12.0,7495.0,10352.0,9271.490256
2,BRAEAR7WZPQGPBZU,9.0,2015-08-18 19:25:22.000,447,Ridge,Yes,Child_care,0,10,0.0,250.0,9.0,5752.0,7309.0,6785.701362

In [96]:
print("Null value check for training data set:")
print(df_train.isnull().sum())

print("\nNull value check for testing data set:")
print(df_test.isnull().sum())

Null value check for training data set:
Product_id            0
Stall_no              5
instock_date          0
Market_Category       0
Customer_name       211
Loyalty_customer      0
Product_Category      0
Grade                 0
Demand                0
Discount_avail       38
charges_1           198
charges_2 (%)       205
Minimum_price        38
Maximum_price       343
Selling_Price        41
dtype: int64

Null value check for testing data set:
Product_id           0
Stall_no             1
instock_date         0
Market_Category      0
Customer_name       53
Loyalty_customer     0
Product_Category     0
Grade                0
Demand               0
Discount_avail       0
charges_1           36
charges_2 (%)        5
Minimum_price       14
Maximum_price        0
dtype: int64

In [97]:
df_train_copy = df_train.copy()
df_test_copy = df_test.copy()

#df_copy.head(10)

#df_train_copy.drop(['Product_id', 'Stall_no', 'instock_date', 'Customer_name'], axis = 1, inplace = True)
df_train_copy.drop(['Customer_name'], axis = 1, inplace = True)
#print(df_train_copy.head(10))

#df_test_copy.drop(['Product_id', 'Stall_no', 'instock_date', 'Customer_name'], axis = 1, inplace = True)
df_test_copy.drop(['Customer_name'], axis = 1, inplace = True)
#print(df_test_copy.head(10))

In [98]:
#### Missing value treatment using Median & mode ####

print("Null value check for training data set before pre processing:")
print(df_train_copy.isnull().sum())

print("\nNull value check for testing data set before pre processing:")
print(df_test_copy.isnull().sum())

if (df_train_copy.isnull().sum().sum() > 0):
    #print("Inside df_train_copy if stmt...")
    df_train_copy['Stall_no'].fillna(df_train_copy['Stall_no'].mode()[0], inplace=True)
    df_train_copy['Discount_avail'].fillna(df_train_copy['Discount_avail'].mode()[0], inplace=True)
    df_train_copy['charges_1'].fillna(df_train_copy['charges_1'].mode()[0], inplace=True)
    df_train_copy['charges_2 (%)'].fillna(df_train_copy['charges_2 (%)'].mode()[0], inplace=True)
    df_train_copy['Minimum_price'].fillna(df_train_copy['Minimum_price'].median(), inplace=True)
    df_train_copy['Maximum_price'].fillna(df_train_copy['Maximum_price'].median(), inplace=True)
    df_train_copy['Selling_Price'].fillna(df_train_copy['Selling_Price'].median(), inplace=True)

if (df_test_copy.isnull().sum().sum() > 0):
    #print("Inside df_test_copy if stmt...")
    df_test_copy['Stall_no'].fillna(df_test_copy['Stall_no'].mode()[0], inplace=True)
    df_test_copy['Discount_avail'].fillna(df_test_copy['Discount_avail'].mode()[0], inplace=True)
    df_test_copy['charges_1'].fillna(df_test_copy['charges_1'].mode()[0], inplace=True)
    df_test_copy['charges_2 (%)'].fillna(df_test_copy['charges_2 (%)'].mode()[0], inplace=True)
    df_test_copy['Minimum_price'].fillna(df_test_copy['Minimum_price'].median(), inplace=True)
    df_test_copy['Maximum_price'].fillna(df_test_copy['Maximum_price'].median(), inplace=True)


print("\nNull value check for training data set after pre processing:")
print(df_train_copy.isnull().sum())

print("\nNull value check for testing data set after pre processing:")
print(df_test_copy.isnull().sum())

Null value check for training data set before pre processing:
Product_id            0
Stall_no              5
instock_date          0
Market_Category       0
Loyalty_customer      0
Product_Category      0
Grade                 0
Demand                0
Discount_avail       38
charges_1           198
charges_2 (%)       205
Minimum_price        38
Maximum_price       343
Selling_Price        41
dtype: int64

Null value check for testing data set before pre processing:
Product_id           0
Stall_no             1
instock_date         0
Market_Category      0
Loyalty_customer     0
Product_Category     0
Grade                0
Demand               0
Discount_avail       0
charges_1           36
charges_2 (%)        5
Minimum_price       14
Maximum_price        0
dtype: int64

Null value check for training data set after pre processing:
Product_id          0
Stall_no            0
instock_date        0
Market_Category     0
Loyalty_customer    0
Product_Category    0
Grade               0
Demand              0
Discount_avail      0
charges_1           0
charges_2 (%)       0
Minimum_price       0
Maximum_price       0
Selling_Price       0
dtype: int64

Null value check for testing data set after pre processing:
Product_id          0
Stall_no            0
instock_date        0
Market_Category     0
Loyalty_customer    0
Product_Category    0
Grade               0
Demand              0
Discount_avail      0
charges_1           0
charges_2 (%)       0
Minimum_price       0
Maximum_price       0
dtype: int64

In [99]:
# To check if the selling price value in training data set is > 0

print("Is there any -ve values in col: Selling_Price: ", any(df_train_copy['Selling_Price']<0))

df_train_copy['Selling_Price'] = abs(df_train_copy['Selling_Price'])

print("Is there any -ve values in col: Selling_Price after treatment: ", any(df_train_copy['Selling_Price']<0))

Is there any -ve values in col: Selling_Price:  True
Is there any -ve values in col: Selling_Price after treatment:  False

In [82]:
#df.head(10)

#### Analyzing the trend between Demand and Selling_Price ####

#plt.scatter(x= df_train_copy['Selling_Price'], y= df_train_copy['Minimum_price'], color='green')
#plt.show()

In [83]:
#plt.scatter(x= df_train_copy['Selling_Price'], y= df_train_copy['Maximum_price'], color='blue')
#plt.show()

In [100]:
##### Converting the column: Loyalty_customer into numeric categorical variable #####

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_train_copy['Loyalty_customer_conv'] = le.fit_transform(df_train_copy['Loyalty_customer'])
df_train_copy['Product_Category_conv'] = le.fit_transform(df_train_copy['Product_Category'])
df_train_copy['Product_id_conv'] = le.fit_transform(df_train_copy['Product_id'])
df_train_copy['instock_date_conv'] = le.fit_transform(df_train_copy['instock_date'])

df_test_copy['Loyalty_customer_conv'] = le.fit_transform(df_test_copy['Loyalty_customer'])
df_test_copy['Product_Category_conv'] = le.fit_transform(df_test_copy['Product_Category'])
df_test_copy['Product_id_conv'] = le.fit_transform(df_test_copy['Product_id'])
df_test_copy['instock_date_conv'] = le.fit_transform(df_test_copy['instock_date'])

#print(df_train_copy.head(10))
#print("\n", df_test_copy.head(10))

In [101]:
df_train_copy.drop(['Loyalty_customer'], axis = 1, inplace = True)  #Dropping the old column: Loyalty_customer from training dataset.
df_train_copy.drop(['Product_Category'], axis = 1, inplace = True)  #Dropping the old column: Product_Category from training dataset.
df_train_copy.drop(['Product_id'], axis = 1, inplace = True)
df_train_copy.drop(['instock_date'], axis = 1, inplace = True)


df_test_copy.drop(['Loyalty_customer'], axis = 1, inplace = True)  #Dropping the old column: Loyalty_customer from test dataset.
df_test_copy.drop(['Product_Category'], axis = 1, inplace = True)  #Dropping the old column: Product_Category from test dataset.
df_test_copy.drop(['Product_id'], axis = 1, inplace = True)
df_test_copy.drop(['instock_date'], axis = 1, inplace = True)

#print(df_train_copy.head(10))
#print("\n", df_test_copy.head(10))

In [146]:
df_train_copy['charges_2'] = df_train_copy['charges_2 (%)']/100
df_test_copy['charges_2'] = df_test_copy['charges_2 (%)']/100


df_train_copy.drop(['charges_2 (%)'], axis = 1, inplace = True)
df_test_copy.drop(['charges_2 (%)'], axis = 1, inplace = True)

In [147]:
df_train_copy = df_train_copy[[col for col in df_train_copy.columns if (col != 'Selling_Price')] + ['Selling_Price']]
df_train_copy.head(3)

,Stall_no,Market_Category,Grade,Demand,Discount_avail,charges_1,Minimum_price,Maximum_price,Loyalty_customer_conv,Product_Category_conv,Product_id_conv,instock_date_conv,charges_2,Selling_Price
0,37.0,2,1,68,0.0,376.0,2983.0,4713.0,1,3,538,1502,0.11,4185.947700
1,38.0,24,0,51,0.0,397.0,7495.0,10352.0,1,3,5946,4732,0.12,9271.490256
2,9.0,447,0,10,0.0,250.0,5752.0,7309.0,1,0,810,1054,0.09,6785.701362

In [211]:
# Dividing the columns that are required for predictions

x1 = pd.DataFrame(df_train_copy.iloc[:,0:13])
y1 = pd.DataFrame(df_train_copy.iloc[:,-1])

y1 = y1.astype('int')

x2 = df_test_copy.copy()

#print(x1)
#print("\n",y1)

In [212]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

#apply SelectKBest class to extract top 10 best features
bestfeatures = SelectKBest(score_func=chi2, k=10)
fit = bestfeatures.fit(x1,y1)

dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(x1.columns)

#concat two dataframes for better visualization.

featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns
print(featureScores.nlargest(10,'Score'))  #print 10 best features

                    Specs         Score
7           Maximum_price  1.192510e+07
6           Minimum_price  7.805354e+06
10        Product_id_conv  4.925744e+06
11      instock_date_conv  4.463066e+06
1         Market_Category  6.779598e+05
5               charges_1  2.592070e+05
3                  Demand  7.480575e+04
0                Stall_no  3.751990e+04
9   Product_Category_conv  8.506275e+03
2                   Grade  7.897880e+03
4          Discount_avail  5.053305e+03
8   Loyalty_customer_conv  1.798877e+03

In [213]:
x1.drop(['Product_Category_conv'], axis = 1, inplace = True)
x1.drop(['Stall_no'], axis = 1, inplace = True)
#x1.drop(['Grade'], axis = 1, inplace = True)
#x1.drop(['Demand'], axis = 1, inplace = True)
#x1.drop(['charges_1'], axis = 1, inplace = True)
#x1.drop(['charges_2'], axis = 1, inplace = True)
#x1.drop(['instock_date_conv'], axis = 1, inplace = True)
x1.drop(['Product_id_conv'], axis = 1, inplace = True)
#x1.drop(['Loyalty_customer_conv'], axis = 1, inplace = True)
#x1.drop(['Discount_avail'], axis = 1, inplace = True)

x2.drop(['Product_Category_conv'], axis = 1, inplace = True)
x2.drop(['Stall_no'], axis = 1, inplace = True)
#x2.drop(['Grade'], axis = 1, inplace = True)
#x2.drop(['Demand'], axis = 1, inplace = True)
#x2.drop(['charges_1'], axis = 1, inplace = True)
#x2.drop(['charges_2'], axis = 1, inplace = True)
#x2.drop(['instock_date_conv'], axis = 1, inplace = True)
x2.drop(['Product_id_conv'], axis = 1, inplace = True)
#x2.drop(['Loyalty_customer_conv'], axis = 1, inplace = True)
#x2.drop(['Discount_avail'], axis = 1, inplace = True)

In [214]:
# Splitting the dataset into the Training set and Test set

#from sklearn.model_selection import train_test_split

#X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

print(x1.isnull().sum())

Market_Category          0
Grade                    0
Demand                   0
Discount_avail           0
charges_1                0
Minimum_price            0
Maximum_price            0
Loyalty_customer_conv    0
instock_date_conv        0
charges_2                0
dtype: int64

In [215]:
from sklearn.linear_model import LinearRegression

LRegressor = LinearRegression()
LRegressor.fit(x1, y1)

#To retrieve the intercept:
print(LRegressor.intercept_)

#For retrieving the slope:
print(LRegressor.coef_)

[511.31710879]
[[ 1.10438045e-01  6.61478674e+01 -6.44544967e-02 -4.40848050e+03
   9.22822990e-01  4.91602481e-01  4.00943393e-01 -2.00732208e+01
   2.63237103e-02  2.19948603e+02]]

In [216]:
# Predicting the result

y_pred = LRegressor.predict(x2)

# To compare the actual output values for X_test with the predicted values
#comp_df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
#comp_df

In [73]:
# Visualizing the comparison result as a bar graph.

#df1 = comp_df.head(25)
#df1.plot(kind='bar',figsize=(16,10))
#plt.grid(which='major', linestyle='-', linewidth='0.5', color='green')
#plt.grid(which='minor', linestyle=':', linewidth='0.5', color='black')
#plt.show()

In [217]:
#Adding the prediction variable in test data-set.
final_test_data = pd.read_csv(r'C:\Users\akash\Desktop\HackerEarth\HackerEarth Machine Learning Challenge - Carnival Wars!\dataset\test.csv')
final_test_data['Selling_Price'] = y_pred
        
final_test_data['Selling_Price'] = abs(final_test_data['Selling_Price']) 

#Creating a new copy of the test data-set with prediced value.
final_test_data.to_csv(r'C:\Users\akash\Desktop\HackerEarth\HackerEarth Machine Learning Challenge - Carnival Wars!\dataset\test_predicted_v1.3.csv', index=False)